import java.util.ArrayList;
import java.util.List;

public class Main {

	public static void main(String[] args) {
	     // Desafio 105 1
        List l = new ArrayList<>();
        int i = 0;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        i +=2;
        l.add(i);
        for(int j=0;j<l.size();j++){
            System.out.println(l.get(j));
        } 
        // Desafio 105 2        
        // O desafio não poderá ser cumprido, a entrada é muito grande. Assim como, minha calculadora não consegue efetutuar o cálculo de 99999999999999999999999999 x 4 bytes + 12 bytes do header, mas seria algo em torno disso o tamanho em bytes da array. Totalmente inviável.

	}

}
